@startuml

actor Ажилтан
actor Менежер

usecase ("Нэвтрэх") as UC_Нэвтрэх
usecase ("Хүлээн авах") as UC_Хүлээн
usecase ("Материал боловсруулах") as UC_МатериалБоловсруулах
usecase ("Хүлээлгэн өгөх") as UC_Хүлээлгэн
usecase ("Тайлан гаргах") as UC_Тайлан

usecase ("Захиалга удирдах") as UC_ЗахиалгаУдирдах
usecase ("Захиалга харах") as UC_ЗахиалгаХарах
usecase ("Захиалга үүсгэх") as UC_ЗахиалгаҮүсгэх
usecase ("Харилцагч удирдах") as UC_Харилцагч
usecase ("Тохиргоо утгууд өөрчлөх") as UC_Тохиргоо

usecase ("Будах") as UC_Будах
usecase ("Холих") as UC_Холих
usecase ("Цувих") as UC_Цувих
usecase ("Ээрэх") as UC_Ээрэх
usecase ("Ороох") as UC_Ороох
usecase ("Давхарлах") as UC_Давхарлах
usecase ("Мушгих") as UC_Мушгих

Ажилтан --> UC_Нэвтрэх
Ажилтан --> UC_Хүлээн
Ажилтан --> UC_МатериалБоловсруулах
Ажилтан --> UC_Хүлээлгэн
Ажилтан --> UC_ЗахиалгаХарах

Менежер --> UC_Нэвтрэх
Менежер --> UC_ЗахиалгаУдирдах
Менежер --> UC_ЗахиалгаҮүсгэх
Менежер --> UC_Харилцагч
Менежер --> UC_Тохиргоо
Менежер --> UC_ЗахиалгаХарах
Менежер -u-> UC_Тайлан

UC_ЗахиалгаУдирдах -[hidden]-> UC_ЗахиалгаХарах : <<include>>
UC_ЗахиалгаУдирдах -[hidden]-> UC_ЗахиалгаҮүсгэх : <<include>>
UC_ЗахиалгаУдирдах -[hidden]-> UC_Харилцагч : <<include>>
UC_ЗахиалгаУдирдах -[hidden]-> UC_Тохиргоо : <<include>>

UC_МатериалБоловсруулах -[hidden]-> UC_Будах : <<include>>
UC_МатериалБоловсруулах -[hidden]-> UC_Холих : <<include>>
UC_МатериалБоловсруулах -[hidden]-> UC_Цувих : <<include>>
UC_МатериалБоловсруулах -[hidden]-> UC_Ээрэх : <<include>>
UC_МатериалБоловсруулах -[hidden]-> UC_Ороох : <<include>>
UC_МатериалБоловсруулах -[hidden]-> UC_Давхарлах : <<include>>
UC_МатериалБоловсруулах -[hidden]-> UC_Мушгих : <<include>>

UC_МатериалБоловсруулах --> UC_Будах : <<include>>
UC_МатериалБоловсруулах --> UC_Холих : <<include>>
UC_МатериалБоловсруулах --> UC_Цувих : <<include>>
UC_МатериалБоловсруулах --> UC_Ээрэх : <<include>>
UC_МатериалБоловсруулах --> UC_Ороох : <<include>>
UC_МатериалБоловсруулах --> UC_Давхарлах : <<include>>
UC_МатериалБоловсруулах --> UC_Мушгих : <<include>>

UC_МатериалБоловсруулах -u-> UC_ЗахиалгаҮүсгэх : <<extend>>
UC_Хүлээлгэн -u-> UC_Тайлан : <<extend>>

@enduml